[package]
name = "swisseph-wasm"
version = "0.1.0"
edition = "2021"
description = "Swiss Ephemeris Bindings for WebAssembly"
license = "MIT"
repository = "https://github.com/fusionstrings/swisseph-wasm"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.105"
js-sys = "0.3.76"
libm = "0.2"
libc = "0.2"

[build-dependencies]
cc = "1.0"
