[package]
name = "swisseph-wasm"
version = "0.1.4"
edition = "2024"
description = "Swiss Ephemeris Bindings for WebAssembly"
license = "MIT"
repository = "https://github.com/fusionstrings/swisseph-wasm"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.106"
js-sys = "0.3.83"
libm = "0.2.15"
libc = "0.2.180"

[build-dependencies]
cc = "1.2.51"
