/* automatically generated by rust-bindgen 0.69.5 */

pub const SE_SUN: u32 = 0;
pub const SE_MOON: u32 = 1;
pub const SE_GREG_CAL: u32 = 1;
pub const SEFLG_SWIEPH: u32 = 2;
pub const SEFLG_SPEED: u32 = 256;
pub const SE_SIDM_LAHIRI: u32 = 1;
pub const SE_SIDM_RAMAN: u32 = 3;
pub const SE_SIDM_KRISHNAMURTI: u32 = 5;
pub const SE_SIDM_TRUE_CITRA: u32 = 27;
